### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by 4www** [internet4000/find#12]
Super important to writte a battery of tests.

With AVA https://github.com/avajs/ava ?

**Comment by oskarrough** [comment]
Can you give some examples of things or methods to test? I can help set it up.

**Comment by 4www** [comment]
Thanks a lot!

I think the first most important test would to be sure that `find(query)` is a pure function, that for a same input, its output does not change across new releases.

For example `find('!m berlin')` should output `https://www.google.com/maps/search/berlin`.

I think we could be starting by this,
so then we now that each of the action/search engines we have will give coherent results.

What do you think?

**Comment by oskarrough** [comment]
I tested a bit:

Find doesn't work in node.js, because we don't use modules and rely on `window`. So we can't use Ava. Instead we need a test runner that runs a browser, like https://www.cypress.io/.

With Cypress, or something similar, we can say `open index.html` and have access to the global scope so we can test `App.find()` directly. This is also what we do in radio4000-player.

Unfortunately it's quite a bit more heavy than Ava. I don't know of any alternatives. What do you think?
